=== spb-metrics/banco-de-talentos/src/main/webapp/WEB-INF/config/Comum/action-plug-in/action-plug-in-config_1_0.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- edited with XML Spy v4.1 U (http://www.xmlspy.com) by Gerrie Kimpen (Home) -->
<!--DTD generated by XML Spy v4.1 U (http://www.xmlspy.com)-->
<!ELEMENT action-plug-in-config (action-plug-in+)>
<!ELEMENT action-plug-in (class, init-params?, (disabled-for+ | enabled-for+))>
<!ELEMENT class (#PCDATA)>
<!ELEMENT init-params (param+)>
<!ELEMENT disabled-for (action-path+)>
<!ELEMENT enabled-for (action-path+)>
<!ELEMENT param (name, value, description?)>
<!ELEMENT action-path (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT value (#PCDATA)>
<!ELEMENT description (#PCDATA)>

=== spb-metrics/banco-de-talentos/src/main/webapp/WEB-INF/config/projeto/action-plug-in/action-plug-in-config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE action-plug-in-config
  PUBLIC "-//ASQdotCOM//DTD Struts Action Plug-In Extension 1.0//EN"
  "http://www.asqdotcom.be/struts/action-plug-in-config_1_0.dtd">
<action-plug-in-config>
    <action-plug-in>
        <class>br.gov.camara.util.actionplugin.plugin.SegurancaActionPlugIn</class>
        <disabled-for>
            <action-path>/indexSigesp</action-path>
            <action-path>/encaminharLogon</action-path>
            <action-path>/encaminharLogoff</action-path>
            <action-path>/validarAutenticacaoExterna</action-path>
            <action-path>/encaminharErro</action-path>
            <action-path>/encaminharUsuarioNaoAutorizado</action-path>
            <action-path>/encaminharAvisoJavaScript</action-path>
            <action-path>/validarLogonEfetuarLogon</action-path>
			<action-path>/validarLogonEncaminharModulo</action-path>
        </disabled-for>
    </action-plug-in>
</action-plug-in-config>
